### ISSUE TITLE
Why is `typeof 0n` not equal to `"bigInt"`?

### ISSUE THREAD

**Issue by dou4cc** [tc39/proposal-bigint#148]

**Comment by ljharb** [comment]
I would expect it to be. What is it, to your reading?

**Comment by dou4cc** [comment]
I mean `typeof 0n` in present, `"bigint"`, does not meet the hump-style naming.

**Comment by ljharb** [comment]
all the typeof values are lowercase - including number, boolean, etc. Why would this one be different?

**Comment by dou4cc** [comment]
That's just coincidental. `"number"`, `"boolean"`, etc are all single words.

**Comment by dou4cc** [comment]
Let's ask @BrendanEich.

**Comment by ljharb** [comment]
I don't think it's coincidental; the number constructor is `Number`, but the typeof value is `number` (same for Symbol, Boolean, String, Object, Function…). Similarly, the constructor might be `BigInt`, but nothing is `bigInt`, and the typeof value seems like it should be `bigint`.

I can see an argument for `BigInt` (one quickly defeated by aforementioned precedent), but I see zero argument for `bigInt`.

**Comment by EthanRutherford** [comment]
I see no argument against, either. Seems rather like an arbitrary choice, with no precedent one way or the other.

**Comment by ljharb** [comment]
The argument against is that "bigInt" isn't a thing - there's a `BigInt`, and there's a precedent for typeof values being all lowercase, but there's no such thing as `bigInt`.

**Comment by EthanRutherford** [comment]
But it's also two words. As I said, it's lacking precedent: no other primitive is composed of two words.
(and there's no such thing as `bigint` either)

`number`, `string`, etc. ***are*** all valid lowerCamelCase strings, so who's to say that the precedent is "all lowercase" as you claim, vs. "lowerCamelCase"? It's not an answerable question, both sides are true. Since there is no precedent for a primitive with a multi-word name, there's nothing to use as evidence to say "see? We use only lowercase, not lowerCamelCase".

So there isn't really an argument either way in my eye. This is the first opportunity anyone has to decide *what* the precedent is, from now on: lowercase, or lowerCamelCase.

**Comment by dou4cc** [comment]
That's my question: which is clearer and more JS-style, lowercase or lowerCamelCase?

**Comment by trotyl** [comment]
HTML/Web seems to prefer lowercase, like using `slotchange` as event name.

**Comment by dou4cc** [comment]
@trotyl HTML 不是全小写而是不区分大小写。

**Comment by trotyl** [comment]
@dou4cc DOM event name is case-sensitive, only attribute name does not.

**Comment by dou4cc** [comment]
@trotyl Event name is still case-insensitive. Forcing lowercase is a kind of normalization.

**Comment by dou4cc** [comment]
@trotyl Also, JS is not designed for Web.

**Comment by ljharb** [comment]
@EthanRutherford ok, let's try another tack. What value do you think it could possibly have to go one way or the other, such that it's worth having this discussion about a stage 3 feature that's already shipping in node and chrome?

**Comment by dou4cc** [comment]
@ljharb Has not shipped in Node.js.

**Comment by trotyl** [comment]
@dou4cc 

![image](https://user-images.githubusercontent.com/6059170/39614885-ac24b090-4fa5-11e8-8883-a26cba8d3ae4.png)
![image](https://user-images.githubusercontent.com/6059170/39614892-bc93a620-4fa5-11e8-8083-02b0392f00a2.png)

You can just try `$0.addEventListener('CLICK', () => console.log(42))` in this page.

**Comment by ljharb** [comment]
@dou4cc `node --harmony-bigint -e 'console.log(typeof 0n)'` in node 10 works just fine.

**Comment by trotyl** [comment]
By saying "HTML/Web" it means "HTML/(WEB API)" as "HTML/(DOM API)/...", and DOM API is more JavaScript related than HTML.

**Comment by dou4cc** [comment]
@ljharb Because this will be a precedent for chaotic UNIX-style naming.

**Comment by lazarljubenovic** [comment]
Guys who did `onclick` probably said the same for `onresourcetimingbufferfull`, though.

We could be going towards making a difference between `int`, `float`, `double`. God only knows what kind of thing could be a primitive in 15 years.

**Comment by littledan** [comment]
@EthanRutherford hit the nail on the head [here](https://github.com/tc39/proposal-bigint/issues/148#issuecomment-386468534):

> I see no argument against, either. Seems rather like an arbitrary choice, with no precedent one way or the other.

The choice of case here is fairly arbitrary. I chose all lowercase here since it looked analogous to the existing primitives, as @ljharb explains above, but at the same time, it's a fair counter-point that we haven't "tested" this with any multi-word primitives yet.

What we're doing here establishes a new convention, one way or the other. HTML events may have an all-lowercase convention, but that's pretty separate from this, AFAICT.
----
This proposal is at Stage 3. To me, that means that the abstract language design should be basically done, and tweaks from here on out should be mostly motivated by implementation/deployment experience. In this context, I'd like to hear a pretty strong reason why `bigInt` is actually better than `bigint` to motivate a change, beyond @dou4cc 's question above, "Which is clearer and more JS-style, lowercase or lowerCamelCase?"

**Comment by trotyl** [comment]
Precedents of string-based notation in JavaScript world:

## camelCase

+  JavaScript Symbol: `Symbol.for('asyncIterator')`

## lowercase

+ DOM API: `el.addEventListener('compositionstart')`
+ Service Worker API: `type: 'sharedworker'`
+ WebAssembly JavaScript API: `element: 'anyfunc'`

## kebab-case

+ JavaScript Atomics: `Atomics.wait() === 'not-equal'`
+ Fetch API: `cache: 'only-if-cached'`
+ Web Animations API: `easing: 'ease-in'`
+ Web Audio API: `channelCountMode: 'clamped-max'`
+ Web Budget API: `reserve: 'silent-push'`
+ Clipboard API: `name: 'clipboard-read'`

**Comment by dou4cc** [comment]
Since the keywords of JS are lowercase, `"bigint"` seems more reasonable than `"bigInt"`, when standing with `typeof`.

**Comment by lazarljubenovic** [comment]
@dou4cc No, they are not lower case. We don't know what they are since they are all a single word. For all we know they could be param-case and snake_case as well.

I understand if people want to make them lowercase (although I disagree with that). But saying that JS keywords are lowercase" is simply false. They're all single words so they are nothing yet. They will become whatever this proposal ends up with.

**Comment by sjrd** [comment]
`instanceof` and `typeof` are definitely 2 words each ;)

**Comment by lazarljubenovic** [comment]
My mind read @dou4cc's _keywords_ as _types_. I apologize. :pray:
