### ISSUE TITLE
Number.isFinite(1n) returns false. That's misleading.

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-bigint#199]

**Comment by ljharb** [comment]
I would expect all Number methods to either work with Bigints or to not work with them; this proposal has decided on the matter - as such, 1n is not a finite *Number*, so I’d expect false.

**Comment by jakobkummerow** [comment]
Personally, I'm inclined to agree that it would be nice if `Number.isFinite` threw a TypeError for BigInt inputs, instead of quietly returning `false`. However, the current behavior naturally emerges from the existing [spec text](https://tc39.github.io/ecma262/#sec-number.isfinite) for `Number.isFinite(number)`:

> 1. If Type(number) is not Number, return false.

So if we wanted to make `Number.isFinite(1n)` throw an exception, then for consistency `Number.isFinite("hello world")` and `Number.isFinite({this_object: "is not a number"})` would also have to throw, which (1) would clearly be a change out of scope for the BigInt proposal, and (2) would go against JavaScript's (controversially debated) tradition of "keeping on trucking", so I'd expect such a proposal to encounter some resistance.

Pragmatically speaking: 
- all BigInts are finite
- BigInts are not Numbers, and are not designed to be interchangeable with Numbers
- most code will probably decide whether it wants to work with BigInts or Numbers, and won't work with both
- if you do have reason to write generic code and need to make the distinction, you can use `typeof`.

**Comment by caiolima** [comment]
Closing this, since this proposal is already complete.
