### ISSUE TITLE
Mixed type comparison operators

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-bigint#2]
Should `<`, `==` be permitted between Numbers and BigInts?

**Comment by not-an-aardvark** [comment]
I would be a bit concerned about throwing with `==` or `===`, since those are currently safe to use between any two arbitrary objects. For example, this function never throws with current semantics:

```js
function foo(num) {
  if (num === 5) doSomething();
}
```

It might be best to do the same thing as Symbols -- throw with operators like `>` and `<`, but still work correctly with `===`.

**Comment by littledan** [comment]
The proposed semantics are in the explainer are that `0 === 0n` would return false, and `0 == 0n` would throw.

Although Symbols don't throw with `==`, there are other cases where `==` already throws, e.g., `1 == {valueOf(){ throw new TypeError() }}` throws a new TypeError. Arguably, however, these are obscure enough that we should not throw for `==` either. What do you think?

**Comment by not-an-aardvark** [comment]
Personally, I think it's unexpected for `==` to throw when comparing two different types, since `==` usually tries to cast the operands. I would expect `==` to always succeed and return a boolean. (Although you make a good point about `1 == {valueOf(){ throw new TypeError() }}` -- I suppose `==` isn't always successful with arbitrary values.)

**Comment by littledan** [comment]
Would you expect `0 == 0n` to return true or false?

**Comment by not-an-aardvark** [comment]
I would expect it to return `true`, because it seems like `0` and `0n` are referring to different representations of the same mathematical value. (That said, I don't use `==` very often, so I might not have a good intuition for how it should behave.)

**Comment by littledan** [comment]
Well, comparison between types like that would be possible. But, in that case, why not support `<`?

**Comment by LeszekSwirski** [comment]
My opinion, and I believe that you've said this before @littledan, is that there are only two reasonable options

  1) === false, =,< etc. is TypeError
  2) === false, =,< defined arithmetically

I'm personally in favour of 2), seems that @not-an-aardvark is too, but I acknowledge that 1) is the safer option in terms of changing our mind in the future. The one counter-argument I can think of against 1), aside from "least surprise", is that if we end up changing to 2) in the future, we may have different browsers with different versions or different vendors which implement both 1) and 2), causing a debugging mini-nightmare.

**Comment by mihailik** [comment]
The biggest focus must be on compatibility.

Lots and lots of existing well-tested, tuned and safe code out there tests inputs:

```javascript
if (x>0 || x<0) ...  (1)

if (x) ...  (2)

if (x<max) ...  (3)

if (x==currentValue) ...  (4)

color = x > 0 ? 'green' : x < 0 ? 'red' : 'black'  (5)
```

During transition, as `Integer` is introduced to one area of the code, it should not destabilise other parts in a catastrophic manner.

It's one thing to prevent arithmetics between `Number` and `Integer`, but at least comparisons should work. Otherwise the value proposition of `Integer` becomes microscopic comparing to the liability of it exploding on touch.

`Symbol` and `{valueOf: function}` can be explosives, but you have to get out of your way to craft them. `Integer` is meant to be everyday common type. Guns are expected to be deadly, but deadly pencil is a big no.

**Comment by littledan** [comment]
@mihailik We could support `==` and `>` as a special case, but it wouldn't create a seamless upgrade path. It's explained in [the explainer](https://github.com/tc39/proposal-integer#no-implicit-conversions-or-mixed-operands) why we can't have mixed operands in general, e.g., for `+`. When transitioning to Integer, users will have to update their code for `+`; if we were to handle that case, they'd lose all benefits from the upgrade (since Number is a perfectly fine way to represent small integers). Instead, the transition will take a bit of work, to apply it everywhere, if users want to enable better precision. Throwing eagerly is a intended to be a way to help users identify all the cases that they need to update, rather than later seeing a more subtle bug of getting the wrong answer.

I don't have a good idea about how to give users an upgrade path that doesn't create some work for them. In @rauschma's [proposal](https://gist.github.com/rauschma/13d48d1c49615ce2396ce7c9e45d4cd1), users sometimes have to switch to different operators to get exact integer behavior.

**Comment by ljharb** [comment]
Since exact integer behavior is what's new, I think that is indeed where the switching cost should lie.

**Comment by mihailik** [comment]
Agree — tradeoffs and transitional pains are inevitable.

We need adjust the mental model here.  A page/app is a **baskets of libraries,** rather than a product of **a user** or even a team. Only a subset of it is under user's control.

In 'basket of libraries' environment, a large share of TypeErrors crash outside your control. External libraries react brittle to Integer type: they throw or not depending on version, or even on uglifier choice.

In practice by enforcing type strictness you'd make behaviour less predictable. Libraries pioneering Integer may even get bad press for being buggy.

**Comment by littledan** [comment]
@mihailik Switching from Integers to Numbers for an API would be a breaking, semver-major change, similar to changing the name of the function. I'd encourage library authors to not do it. The idea of Integer is to be used for new things which were not possible before using Number. Do you think there's a way to communicate this to library authors before they break their users' code in ways beyond the users' control as you mention is a bad possibility? Even if they don't crash, they will give users bad answers. A reasonable alternative here would be to abandon the Integer proposal, if there's no good way to get the intended behavior while reaching user expectations.

@ljharb I'm not sure what you mean. How would one choice or another choice of TypeError vs downcast behavior put the switching cost on the users who want exact semantics?

**Comment by not-an-aardvark** [comment]
I agree with some of what @mihailik is saying. It would be nice to have Integer behave as a subtype of Number (similar to what python3 does).  For example, if a value in my API represents an array index, I could make stronger guarantees about it by switching it to an Integer. I think being able to use Integers as a drop-in replacement for Numbers would significantly increase their adoption, but this won't work if Integers are incompatible with Numbers for common uses such as adding 1.

Floats stop being safe at 2<sup>53</sup>, so it wouldn't be possible for the subtyping to be completely sound if Integers have arbitrary precision. It's worth noting that most applications don't use values above 2<sup>53</sup> anyway, so while we should still account for this case, it might be better to make Integers more usable in the common case.

If Integers are incompatible with Numbers and throw on comparison/addition, then libraries won't be able to support Integers and Numbers simultaneously. For a return value which is a mathematical integer, library authors will have to choose between correctness for values above 2<sup>53</sup> (usually an esoteric concern) and ease-of-use in the common case (e.g. users will often have to explicitly cast returned Integers to Numbers to prevent errors from being thrown when passing them to other functions). I suspect this will lead to very low adoption of Integers.

Could we allow seamless behavior when adding Integers and Numbers whose value is a safe integer? If we make `1n + 1 === 2n`, then we could avoid avoid precision loss/domain issues when adding, and it would make it easier for libraries to migrate to returning Integers without breaking everything else. (Doing something like `getSomeIntegerValue() + 1 + 2.5` would still cause an error, but I suspect this would happen much more rarely.)

**Comment by rauschma** [comment]
@not-an-aardvark @mihailik: In many ways, @littledan’s proposal is the cleanest way of introducing big ints. As Dan mentioned, you can integrate big ints more transparently if you are willing to use new operators for some operations: https://gist.github.com/rauschma/13d48d1c49615ce2396ce7c9e45d4cd1

**Comment by bakkot** [comment]
> I think being able to use Integers as a drop-in replacement for Numbers would significantly increase their adoption [... ]It's worth noting that most applications don't use values above 2^53 anyway, so while we should still account for this case, it might be better to make Integers more usable in the common case.

This I think is a confusion about what this proposal is for.

The point of BigInteger is to do something which previously *was not possible* without a great deal of effort and overhead, i.e., work with integers above 2^53. That's the case we should care about. Applications which don't use integers about 2^53 should not use BigIntegers.

I don't think we want BigIntegers be adopted by people who don't need big integers. I don't see low adoption there as a problem.

**Comment by mihailik** [comment]
How about `throw on overflow/underflow/loss of precision` policy?

The check happens at runtime, so we know exactly whether `myInt + myNumber` is kosher or not.

**Comment by bakkot** [comment]
@mihailik that seems [worse still](https://github.com/tc39/proposal-integer/issues/24#issuecomment-290382206).

**Comment by not-an-aardvark** [comment]
@bakkot To clarify, I think that lack of common-case ergonomics would be a relevant problem even for applications that use values above 2<sup>53</sup>. If Numbers and Integers are incompatible, libraries will only support Numbers, so applications that use large values will be unable to use many libraries that would otherwise be useful.

**Comment by mihailik** [comment]
@bakkot you're falling into the same misleading writer/consumer mindset.

JS reality is a graph of interdependencies. And that means you have to take date from library A **probably** using Integers and pass it to library B **maybe** using Numbers. There's no good clue to Integer/Number compatibility — indeed some libraries will oscillate between pass and crash based on minute weather.

Your point in [worse still](https://github.com/tc39/proposal-integer/issues/24#issuecomment-290382206) actually goes against strict safety. Forcing a throw means less predictability.

You, writing JS code cannot be sufficiently sure of the external library 'Integerness'. Purely practical reasons: JS lack of safety, wide usage of uglifiers/bundlers and constant stream of updates to any 3rd party library. Neither can you declare 'Integerness' of your library to external callers.

**Comment by mihailik** [comment]
And also, if Integers are not meant for APIs between libraries, why not library approach instead?

Whole new 1st-class language syntax just for calculations **within** some compression library — that's lots of risk for medium-sized reward. Niche code should be fine with `new Integer(100).add(new Integer(200))`.

**Comment by mihailik** [comment]
`function Order(id, ticker, qty, price) {
  this.id = id; ...
}`

Can I use Integer `id` in this library? **Probably** yes.

How about this, any arguments compatible with Integer?

`class SyntaxNodeBase {
  constructor(nodeType, offsetStart, offsetEnd) ...
}`

Looks legit too, isn't it? You just never with this stuff — and due to historical limitations, in any complex libraries it **will** oscillate around throw/pass based on minute circumstances. Such as all the simple values of enum-like argument would pass, but combinations throw, due to === having different rule than &.

**Comment by bakkot** [comment]
@not-an-aardvark , @mihailik

> If Numbers and Integers are incompatible

Numbers and BigIntegers *are* incompatible, regardless of what we do with mixed type operators: they have mutually incompatible precisions. You can't ever trust that code written for one will work for the other.

> Your point in worse still actually goes against strict safety. Forcing a throw means less predictability.

Er. I disagree that "always throws when you try to add a number and a BigInteger" is less predictable than either of "sometimes throws when you try to add a number and a BigInteger, depending on each of their values" or "never throws, but sometimes loses precision in one direction or the other". What do you mean?

> if Integers are not meant for APIs between libraries,

BigIntegers are appropriate for APIs between libraries *which work with large integers*. They are not appropriate for APIs between libraries which do not both operate on large integers. Again, this is the case regardless of what we do with mixed type operators because numbers and BigIntegers have mutually incompatible precisions.

I don't think the presence or absence of literal syntax will have much effect either way on the topic at hand. The question is about what to do with a BigInteger once you have one.

**Comment by mihailik** [comment]
@bakkot the behaviour at a library level is less predictable under the currently proposal, than with a relaxed proposal.

The current proposal throws/passes depending on specific operation. And as you go into nitty-gritty it will only get more specialcased with all the ==, ===, if, switch/case, Date coercion etc.

Looking at any given library API this proposal doesn't provide a sufficient certainty about its Integerness leaning.

Should nodeType above be Integer? Can it handle Integer? Does it require Integer? Even looking at SyntaxNodeBase implementation isn't enough — derived classes may have their own quirks. And specifically with enum-like fields the code would be very prone to oscillations, as sometimes you use === and sometimes & and |. It works with 29, breaks with 32 ooops!

The relaxed proposal might go like `avoid throwing unless data loss`.

If you look at one operation, your intuition is correct: strict safety helps. If you consider JS practices, and look at pragmatic libraries/apps, it actually makes things brittle and unpredictable.

**Comment by bakkot** [comment]
> the behaviour at a library level is less predictable under the currently proposal, than with a relaxed proposal.

Why? How is "always throws" less predicatable than "may or may not throw depending on the exact value"?

> Should nodeType above be Integer? Can it handle Integer? Does it require Integer?

The lack of type annotations isn't really a new problem caused by this proposal. Just looking at the signature it's not obvious if nodeType can be a string, or a Symbol. That it is also not obvious if it can be an Integer isn't a new issue.

With the proposal as-is, you can generally rely on:

- if the API is said to take a value of any type, it will work with BigIntegers (Almost always. The rare failures will not be much more rare than those caused by the introduction of Symbol.)
- if it takes a number, it cannot be trusted to work with BigIntegers.

I continue to be confused by why you think this is less predictable than "if it takes a number, it probably works with BigIntegers unless the BigInteger's value is above some unknown library-implementation-dependent threshold".

> It works with 29, breaks with 32 ooops!

Uh. Avoiding this is exactly the argument *for always throwing*. The "avoid throwing unless data loss" strategy is the only one which would have this issue.

**Comment by mihailik** [comment]
@bakkot the current proposal does not 'always throw'. See difference between == and ===.

Are toy suggesting ALWAYS to throw? Do you throw bigInt + str?

**Comment by littledan** [comment]
@mihailik I had previously proposed that we use method or function syntax for operations on new numeric types, but @BrendanEich pushed operator overloading as a mechanism for being more ergonomic and easy to use.

bigInt + str doesn't throw, but this falls out of everything else: adding to a str always coerces to a String, and Integers have a well-defined coercion to Strings, just not to Numbers.

@not-an-aardvark For use cases that you describe, which usually stay in 2<sup>53</sup> range, I *would* like to discourage people from migrating to Integer. This proposal is about enabling different behavior, not about putting more proper type tags on existing code. For this reason, we're considering changing the name back to BigInt or BigInteger.

**Comment by bakkot** [comment]
@mihailik

Sorry, I should have said "throwing for arithmetic operations mixing BigIntegers and numbers, regardless of their values".

**Comment by mihailik** [comment]
@bakkot hence the rules are well-defined at individual operation level, but unpredictable when looking at a whole library. See examples above, Order and SyntaxNodeBase.

**Comment by bakkot** [comment]
@mihailik 

See:

> The lack of type annotations isn't really a new problem caused by this proposal. Just looking at the signature it's not obvious if nodeType can be a string, or a Symbol. That it is also not obvious if it can be an Integer isn't a new issue.

and

> - if the API is said to take a value of any type, it will work with BigIntegers (Almost always. The rare failures will not be much more rare than those caused by the introduction of Symbol.)
> - if it takes a number, it cannot be trusted to work with BigIntegers.
> 
> I continue to be confused by why you think this is less predictable than "if it takes a number, it probably works with BigIntegers unless the BigInteger's value is above some unknown library-implementation-dependent threshold".

**Comment by mihailik** [comment]
@bakkot let me help you with the meaning of 'unpredictable', consider these questions below.

can I pass `Integer` into `jQuery.width` ?
can I pass `Integer` into `Order` object above ?
can I pass `Integer` into any of the `SyntaxNodeBase` constructor arguments above ?

'Unpredictable' here means you cannot know the results without a very non-trivial research. As opposed to situation where `Number` and `Integer` are more compatible, and thus you can answer those 3 questions above with a simple reasoning: yes, yes and yes to all three arguments.

**Comment by bakkot** [comment]
@mihailik 

> yes, yes and yes to all three arguments 

This is not the case. Because there are some mixed type operations which *must* either throw or silently lose precision - like `9007199254740993n + 0.1` - you can never trust that any function designed to take a number will work with a BigInteger without reading its implementation and reasoning about the semantics of IEEE floats. This is significantly less predictable than "no, you can't use a BigInteger in place of a number".

(Also: can you pass a string to `jQuery.width`, `Order`, or `SyntaxNodeBase`? I maintain that "you can't tell which types a function accepts just from its signature" is not a new problem.)

**Comment by mihailik** [comment]
@bakkot when you say `That is not the case` — which of these **yeses above** are you contesting?

**Comment by bakkot** [comment]
@mihailik All of them. You can't know that without reading the implementation.

**Comment by mihailik** [comment]
@bakkot to quote yourself, `"That is not the case."` A common layman JS developer don't have to read the implementation of jQuery.width to realise 2^54 is not going to cause any more problems than 2^30.

That is what us pragmatic people call 'predictable': the probability being either indistinguishable from 0, or indistinguishable from 1.

**Comment by littledan** [comment]
@mihailik Ultimately, we cannot satisfy the all developer intuitions.

For example, a programmer might not understand the distinction between Strings and Numbers. They'll see that many arithmetic operations work just fine if you pass in Strings. But then, if you pass in a String representing a Number into some libraries, it won't work! Some library function may use `+` internally, and then go back to an arithmetic operator, resulting in `NaN`, or users may find that `==` unexpectedly returns `false` on `"1+2" == 3`.

Many developers probably intuit that Number *already* has exact Integer (or even BigDecimal) semantics where they would want it, and this proposal does not make that the case either.

I want to be pragmatic about this too. This is hard, but maybe there's some way we can investigate further *how much* of a problem this all is.

**Comment by littledan** [comment]
Well, ultimately, at the March 2017 TC39 meeting, the consensus was that we *should* allow such mixed comparisons, for both == and <. I'll patch the spec for this. We can always revert it if we change our minds again; I didn't understand the consensus until now as I was calling in.
