### ISSUE TITLE
ToBigInt conversion of empty string

### ISSUE THREAD

**Issue by GeorgNeis** [tc39/proposal-bigint#66]
The first comment in StringToBigInt implies that the empty string does not match the StringNumericLiteral grammar and that ToNumber converts it to NaN, but neither is the case. The empty string is a valid StringNumericLiteral and ToNumber converts it to +0.

I suggest changing that comment to something like ```If the grammar fails to apply, rather than returning NaN, return error.``` (or maybe even not modifying the algorithm and just using NaN as sentinel). As a consequence, ToBigInt will convert the empty string to 0n. This will also get rid of the need for step 6c in Abstract Equality Comparison.

**Comment by littledan** [comment]
Thanks for this issue; not sure how I made this mistake. I think I was looking at the JS grammar rather than the conversion grammar. Will definitely fix this.

I was hoping to make BigInt parsing a bit more minimal than permissive Number parsing. It does not allow decimals, and maybe it should also not allow whitespace before or after, or empty strings.

I'll start with your suggestion.
