### ISSUE TITLE
disallow hexadecimal literals?

### ISSUE THREAD

**Issue by leobalter** [tc39/proposal-bigint#76]
`0xabcdefn` is weird. Should we allow this literal notation?

cc @rwaldron

**Comment by rwaldron** [comment]
I'd like to request that this proposal explicitly define **Static Semantics: Early Errors** that disallow the following: 

_BinaryIntegerLiteral_ _NumericLiteralSuffix_
_OctalIntegerLiteral_ _NumericLiteralSuffix_
_HexIntegerLiteral_ _NumericLiteralSuffix_


- As @leobalter noted, `n` appears to be a valid hex digit, which hopefully no one ever thinks is true, but it's strange to see that considered "valid". 
- In the same spirit, these are also weird and pointless: `0b1n`, `0o0n` and so on...

**Comment by littledan** [comment]
Well, this feature was specifically requested by multiple other people reviewing the proposal. I don't really understand the problem--n is not a hexadecimal digit.

It seems to me like hex BigInt literals will be genuinely useful--if you have a big hex number, you can write it as a literal. For example, you may copy a hash or GUID from somewhere into JS. If we don't include hex BigInt literals, we risk people making bugs like `BigInt(0x98724347fabcdef298723439789)`, which would lose precision.

**Comment by thejoshwolfe** [comment]
FWIW, I've already started using the hex notation in tests because the character-wise mapping between hex and binary made it easier to reason about the number. https://github.com/tc39/test262/pull/1191/files#diff-a860f8b84187b0ef6ea2b7b54623ac22R55

Without hex notation, I would use Python to convert from hex and decimal, paste the decimal representation into the test, and then put the hex representation in a comment right above it so that a reader can understand why such a specific number was chosen.

I vote keep the hex notation.

**Comment by rwaldron** [comment]
After further consideration, I've determined that my concern was for the learning process, and new users of the language (or programming in general).
