### ISSUE TITLE
Throw on undefined exponentiation usages?

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-bigint#9]
If you take a BigInt and raise it to a negative power, the answer will always be in the range between -1 and 1 (exclusive), which would round to zero if we take division-like semantics. I see a couple options for semantics:
1. Throw an exception, as the user is likely to not get the kind of answer they were hoping for
1. Return 0

Which is better? I'm starting with the first option it the draft spec (following a general "throw first, ask questions later" strategy), but I'd be interested in other opinions, and this probably deserves a comparative look at the semantics of other libraries.

**Comment by littledan** [comment]
There's also the special case of negative exponents of 0, which has an even stronger argument for throwing (based on the results of #7).

**Comment by kgryte** [comment]
For reference, in Python, raising an integer to a negative power results in type promotion.

```
>>> type(2**2)
<type 'int'>
>>> type(2**-2)
<type 'float'>
>>>
```
In contrast, Julia throws a domain error.

```
julia> typeof(2^2)
Int64

julia> 2^-2
ERROR: DomainError:
Cannot raise an integer x to a negative power -n. 
Make x a float by adding a zero decimal (e.g. 2.0^-n instead of 2^-n), or write 1/x^n, float(x)^-n, or (x//1)^-n.
 in power_by_squaring at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in ^ at /Applications/Julia-0.4.2.app/Contents/Resources/julia/lib/julia/sys.dylib
```

In this case, I believe throwing an exception is a better solution. Returning `0` could lead to silent bugs.

**Comment by littledan** [comment]
Another aspect of this issue is whether `0n**0n` should throw. The current spec returns `1n`. Thanks to Waldemar Horwat for raising the issue.

**Comment by kgryte** [comment]
In Julia,

```
julia> 2^0
1
julia> typeof(2^0)
Int64
```
I agree with the current spec behavior where `0n**0n == 1n`.

**Comment by LeszekSwirski** [comment]
I would agree with `0n ** 0n == 1n`. The reason is that polynomial expressions, of the form

```
sum_n (a_n * x_n ** n)
```

can be well defined to a_n at x_n == 0.

**Comment by bakkot** [comment]
There is [no strong consensus](https://en.wikipedia.org/wiki/Exponentiation#Zero_to_the_power_of_zero) on whether the mathematical value `0^0` ought to be defined to be 1 or considered to be undefined, in general.

For IEEE floats, `pow` of (0, 0) gives 1, which is the standard a lot of languages have adopted (including JS).

But languages which have an arbitrary-precision integer type are more likely to treat it as undefined: for example, Mathematica says it is undefined, and Python's `Decimal` throws. (There's no agreement here either, though: GMP [defines it to be](https://gmplib.org/manual/Integer-Exponentiation.html#Integer-Exponentiation) 1.)

Honestly I could go either way. I'd probably lean towards saying `0n**0n === 1n`, because it makes number theory easier and the fact that we're only working with integers, not rational or real numbers, means there's less reason to worry about analysis (where trying to assign it a value is more likely to be a mistake).

**Comment by claudepache** [comment]
The reason for defining 0<sup>0</sup> as undefined is basically that otherwise, (x, y) → x<sup>y</sup> would be discontinuous. That concern does not apply here, since we are not working with a continuous set of numbers (or an approximation thereof). So, definitely. `0n ** 0n === 1n`.

**Comment by littledan** [comment]
@bakkot Why check Python Decimal when ordinary integers in Python already overflow into longs? In Python, it looks like `0 ** 0 == 0L ** 0L == 1`. Ruby seems to have this behavior as well.

Seems like it's not a bad decision to stick with the current spec text, which specifies `0n ** 0n` is `1n`,
